default: &default
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= (ENV['RAILS_MAX_THREADS'].presence || 16).to_i %>

development: &development
  <<: *default
  database: feedadoc_development
  username: feedadoc
  password: password1

test:
  <<: *default
  database: feedadoc_test
  username: feedadoc
  password: password1

production:
  <<: *default
