vagrant:
  database: ccn_development
  username: postgres
  password:

default: &default
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  encoding: unicode
  pool: <%= (ENV['RAILS_MAX_THREADS'].presence || 16).to_i %>

development: &development
  <<: *default
  database: ccn_development
  username: ccn
  password: password1

test:
  <<: *default
  database: ccn_test
  username: ccn
  password: password1

production:
  <<: *default
